# --- CONFIGURAZIONE DATABASE (PostgreSQL - Docker) ---
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/bugboard_db}
spring.datasource.username=${DB_USER:bugboard_user}
spring.datasource.password=${DB_PASS:bugboard_pass}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Aggiorna il DB automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- CONFIGURAZIONE JWT ---
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Durata del token in millisecondi (86400000 = 1 giorno)
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# --- CONFIGURAZIONE UPLOAD FILE ---
# Risolve l'errore se si carica un'immagine più grande di 1MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
